version: '3'
services:
  test.api:
    image: docker.pkg.github.com/Zorbik/test-api/test-api:develop
    container_name: test-api
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./.env:/app/.env